// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: PowerPico

#include "../ui.h"
#include "./ui_PPSPage.h"
#include "key.h"
#if POWER_PICO_UI_MODERN
#include "../modern/ui_modern.h"
#endif

lv_obj_t * ui_SetPage = NULL;
// backlight
static lv_obj_t * ui_PanelBL = NULL;
static lv_obj_t * ui_SliderBL = NULL;
static lv_obj_t * ui_LabelBL = NULL;
// key sound
static lv_obj_t * ui_PanelKS = NULL;
static lv_obj_t * ui_SwitchKS = NULL;
static lv_obj_t * ui_LabelKS = NULL;
// language
static lv_obj_t * ui_PanelLang = NULL;
static lv_obj_t * ui_SwitchLang = NULL;
static lv_obj_t * ui_LabelLang = NULL;
// chose rotation
static lv_obj_t * ui_PanelRotate = NULL;
static lv_obj_t * ui_LabelRotation = NULL;
static lv_obj_t * ui_LabelRotNum = NULL;
// current range mode
static lv_obj_t * ui_PanelRange = NULL;
static lv_obj_t * ui_LabelRange = NULL;
static lv_obj_t * ui_LabelRangeMode = NULL;
// enable PPS, goto PPS page
static lv_obj_t * ui_PanelPPS = NULL;
static lv_obj_t * ui_LabelPPS = NULL;
// about
static lv_obj_t * ui_PanelAbout = NULL;
static lv_obj_t * ui_LabelAbout = NULL;

#if POWER_PICO_UI_MODERN
static lv_obj_t *ui_PanelTheme, *ui_LabelTheme, *ui_ThemeValue;
static lv_obj_t *panels[8];
#else
static lv_obj_t * panels[7]; // 存储所有 panel 的指针
#endif
static int current_panel_index = 0; // 当前选中的 panel 索引
static lv_timer_t *brightness_timer;
static int brightness_direction;
static bool brightness_dirty;
static uint32_t brightness_tick, brightness_changed_at;
static void brightness_stop(void);
static void scroll_focus(void)
{
    lv_obj_update_layout(ui_SetPage);
    lv_area_t row, screen;
    lv_obj_get_coords(panels[current_panel_index], &row);
    lv_obj_get_coords(ui_SetPage, &screen);
    int32_t delta = 0;
#if POWER_PICO_UI_MODERN
    const int top_margin = 43;
#else
    const int top_margin = 12;
#endif
    if (row.y1 < screen.y1 + top_margin) delta = row.y1 - screen.y1 - top_margin;
    else if (row.y2 > screen.y2 - 12) delta = row.y2 - screen.y2 + 12;
    if (delta)
        lv_obj_scroll_to_y(ui_SetPage, lv_obj_get_scroll_y(ui_SetPage) + delta,
                           UI_THEME_ANIM);
}
#if POWER_PICO_UI_MODERN
static lv_obj_t *ui_ModernSettingsTitle;
static lv_obj_t *ui_ModernBLValue;
static lv_obj_t *ui_ModernIcons[7];

static void brightness_geometry(lv_obj_t *slider, lv_area_t *track,
                                 lv_area_t *fill, lv_area_t *knob)
{
    lv_obj_get_coords(slider, track);
    int32_t min = lv_slider_get_min_value(slider);
    int32_t range = lv_slider_get_max_value(slider) - min;
    int32_t value = lv_slider_get_value(slider) - min;
    int32_t height = lv_area_get_height(track);
    int32_t travel = lv_area_get_width(track) - height;
    int32_t offset = range > 0 ? travel * value / range : 0;
    *knob = *track;
    knob->x1 += 1 + offset;
    knob->x2 = knob->x1 + height - 3;
    knob->y1 += 1;
    knob->y2 -= 1;
    *fill = *track;
    fill->x1 += 3;
    fill->y1 += 3;
    fill->y2 -= 3;
    fill->x2 = knob->x2 - 2;
}

static void brightness_draw(lv_event_t *event)
{
    lv_obj_t *slider = lv_event_get_current_target(event);
    lv_layer_t *layer = lv_event_get_layer(event);
    lv_area_t track, fill, knob;
    brightness_geometry(slider, &track, &fill, &knob);
    /* Separate fill inset from thumb travel; native slider padding couples them. */
    lv_draw_rect_dsc_t dsc;
    lv_draw_rect_dsc_init(&dsc);
    dsc.radius = lv_area_get_height(&track) / 2;
    dsc.bg_color = lv_obj_get_style_bg_color(slider, LV_PART_MAIN);
    lv_draw_rect(layer, &dsc, &track);
    if (lv_slider_get_value(slider) > lv_slider_get_min_value(slider)) {
        dsc.radius = lv_area_get_height(&fill) / 2;
        dsc.bg_color = lv_obj_get_style_bg_color(slider, LV_PART_INDICATOR);
        lv_draw_rect(layer, &dsc, &fill);
    }
    dsc.radius = lv_area_get_height(&knob) / 2;
    dsc.bg_color = lv_obj_get_style_bg_color(slider, LV_PART_KNOB);
    dsc.border_width = 2;
    dsc.border_color = lv_obj_get_style_border_color(slider, LV_PART_KNOB);
    lv_draw_rect(layer, &dsc, &knob);
}

static void modern_settings_focus(void)
{
    for (unsigned i = 0; i < sizeof(panels) / sizeof(panels[0]); ++i) {
        bool selected = i == (unsigned)current_panel_index;
        for (unsigned j = 0; j < lv_obj_get_child_count(panels[i]); ++j) {
            lv_obj_t *child = lv_obj_get_child(panels[i], j);
            if (lv_obj_check_type(child, &lv_label_class)) {
                const lv_font_t *font = lv_obj_get_style_text_font(child, 0);
                if (font == ui_round_font18() || font == &ui_font_menu_bold17)
                    lv_obj_set_style_text_font(child,
                        selected ? &ui_font_menu_bold17 : ui_round_font18(), 0);
                lv_obj_set_style_text_color(child, lv_color_hex(selected ? M_WHITE : M_TEXT), 0);
            }
            if (lv_obj_check_type(child, &lv_switch_class)) {
                lv_obj_set_style_bg_color(child, lv_color_hex(selected ? M_WHITE : M_LINE), LV_PART_MAIN);
                lv_obj_set_style_bg_color(child, lv_color_hex(selected ? M_WHITE : M_CYAN), LV_PART_INDICATOR);
                lv_obj_set_style_bg_color(child, lv_color_hex(selected ? M_CYAN : M_WHITE),
                                           LV_PART_KNOB);
            }
        }
        if (i < 7)
            lv_obj_set_style_text_color(ui_ModernIcons[i],
                                       lv_color_hex(selected ? M_WHITE : M_CYAN), 0);
    }
    bool selected = current_panel_index == 0;
    lv_obj_set_style_bg_color(ui_SliderBL, lv_color_hex(selected ? M_WHITE : M_LINE), LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_SliderBL, lv_color_hex(M_CYAN), LV_PART_INDICATOR);
    lv_obj_set_style_bg_color(ui_SliderBL, lv_color_hex(selected ? M_CYAN : M_WHITE), LV_PART_KNOB);
    lv_obj_set_style_border_color(ui_SliderBL, lv_color_hex(selected ? M_WHITE : M_CYAN), LV_PART_KNOB);
    char value[8];
    uint8_t level = (uint8_t)((lv_slider_get_value(ui_SliderBL) + 5) / 10);
    snprintf(value, sizeof(value), "%u%%", (unsigned)level);
    lv_label_set_text(ui_ModernBLValue, value);
}
#endif

static void brightness_save(void)
{
    if (brightness_dirty) {
        ui_system_settings_save();
        brightness_dirty = false;
    }
}

static void brightness_apply(int units)
{
    if (units < 100) units = 100;
    if (units > 1000) units = 1000;
    if (units == lv_slider_get_value(ui_SliderBL)) return;
    lv_slider_set_value(ui_SliderBL, units, LV_ANIM_OFF);
    uint8_t level = (uint8_t)((units + 5) / 10);
    if (level != ui_get_back_light_level()) {
        ui_set_back_light_level(level);
        brightness_dirty = true;
        brightness_changed_at = lv_tick_get();
    }
#if POWER_PICO_UI_MODERN
    char value[8];
    snprintf(value, sizeof(value), "%u%%", (unsigned)level);
    lv_label_set_text(ui_ModernBLValue, value);
#endif
}

static void brightness_update(lv_timer_t *timer)
{
    uint32_t now = lv_tick_get();
    if (brightness_direction) {
        uint32_t mask = Key_GetPressedMask() & (KEY_BIT(KEY_ID_Y) | KEY_BIT(KEY_ID_N));
        uint32_t expected = KEY_BIT(brightness_direction > 0 ? KEY_ID_Y : KEY_ID_N);
        if (current_panel_index != 0 || mask != expected) {
            brightness_stop();
            return;
        }
        /* Fractional slider units; the existing PWM/settings API stays in %. */
        uint32_t elapsed = now - brightness_tick;
        if (elapsed > 80U) elapsed = 80U;
        brightness_tick = now;
        brightness_apply(lv_slider_get_value(ui_SliderBL) +
                         brightness_direction * (int)(elapsed / 4U));
    } else if (now - brightness_changed_at >= 300U) {
        brightness_save();
        lv_timer_pause(timer);
    }
}

static void brightness_stop(void)
{
    brightness_direction = 0;
    if (brightness_timer) lv_timer_pause(brightness_timer);
    brightness_save();
}

static void brightness_key(const key_event_t *key)
{
    int direction = key->id == KEY_ID_Y ? 1 : -1;
    if (key->type == KEY_EVT_CLICK) {
        brightness_direction = 0;
        int level = (lv_slider_get_value(ui_SliderBL) + 5) / 10;
        brightness_apply((level + direction) * 10);
        lv_timer_resume(brightness_timer);
        lv_timer_reset(brightness_timer);
    } else if (key->type == KEY_EVT_LONG) {
        brightness_direction = direction;
        brightness_tick = lv_tick_get();
        lv_timer_resume(brightness_timer);
        lv_timer_reset(brightness_timer);
    }
    /* REPEAT does not drive the ramp; release is checked from stable key state. */
}

#include "gate.h"
static void _set_range_label_text(uint8_t mode)
{
    if (mode == GATE_MODE_AUTO) {
        lv_label_set_text(ui_LabelRangeMode, _("AUTO"));
    } else if (mode == GATE_MODE_LOW) {
        lv_label_set_text(ui_LabelRangeMode, _("LOW"));
    } else if (mode == GATE_MODE_MID) {
        lv_label_set_text(ui_LabelRangeMode, _("MID"));
    } else {
        lv_label_set_text(ui_LabelRangeMode, _("HIGH"));
    }
}

static void set_translated_label(lv_obj_t *label, const char *text,
                                 const lv_font_t *english_font,
                                 const lv_font_t *chinese_font)
{
    lv_obj_set_style_text_font(label,
        ui_get_language_select() ? chinese_font : english_font, 0);
    lv_label_set_text(label, _(text));
}

static void refresh_language(void)
{
#if POWER_PICO_UI_MODERN
    lv_obj_t *labels[] = {ui_LabelBL, ui_LabelKS, ui_LabelLang, ui_LabelRotation, ui_LabelRange, ui_LabelPPS};
    const char *text[] = {m_lang("Brightness", "屏幕亮度"), m_lang("Key sound", "按键声音"),
        m_lang("Chinese", "中文显示"), m_lang("Rotation", "屏幕旋转"),
        m_lang("Range", "电流量程"), m_lang("Power control", "电源调节")};
    for (unsigned i = 0; i < 6; ++i) {
        lv_label_set_text(labels[i], text[i]);
        lv_obj_set_style_text_font(labels[i], ui_round_font18(), 0);
    }
    lv_label_set_text(ui_ModernSettingsTitle, m_lang("Settings", "设置"));
    lv_obj_set_style_text_font(ui_ModernSettingsTitle, &ui_font_title17, 0);
    lv_obj_set_style_text_font(ui_LabelRangeMode, ui_round_font18(), 0);
    lv_obj_set_style_text_font(ui_ModernBLValue, ui_round_font18(), 0);
    lv_obj_set_style_text_font(ui_LabelRotNum, ui_round_font18(), 0);
    lv_obj_set_style_text_font(ui_LabelAbout, ui_round_font18(), 0);
    lv_label_set_text(ui_LabelTheme, m_lang("Theme", "主题"));
    lv_label_set_text(ui_ThemeValue, ui_palette_name(ui_palette_index()));
#else
    set_translated_label(ui_LabelBL, "Screen Brightness :",
                        &lv_font_montserrat_16, &ui_font_zhongyuan18);
    set_translated_label(ui_LabelKS, "Enable key sound",
                        &lv_font_montserrat_16, &ui_font_zhongyuan18);
    set_translated_label(ui_LabelLang, "Enable Chinese",
                        &lv_font_montserrat_16, &ui_font_zhongyuan18);
    set_translated_label(ui_LabelRotation, "Chose Rotation",
                        &lv_font_montserrat_16, &ui_font_zhongyuan18);
    set_translated_label(ui_LabelRange, "Current Range",
                        &lv_font_montserrat_16, &ui_font_zhongyuan18);
    set_translated_label(ui_LabelPPS, "PD Sink",
                        &lv_font_montserrat_18, &ui_font_zhongyuan20);
    lv_obj_set_style_text_font(ui_LabelRangeMode, ui_get_language_select()
        ? &ui_font_zhongyuan18 : &lv_font_montserrat_18, 0);
#endif
    _set_range_label_text(ui_get_current_range_mode());
    if (ui_get_language_select()) {
        lv_obj_add_state(ui_SwitchLang, LV_STATE_CHECKED);
    } else {
        lv_obj_clear_state(ui_SwitchLang, LV_STATE_CHECKED);
    }
}

static void change_language(uint8_t language)
{
    if (language == ui_get_language_select()) return;
    if (lv_i18n_set_locale(language ? "zh-cn" : "en") != 0) return;
    ui_set_language_select(language);
    refresh_language();
#if POWER_PICO_UI_MODERN
    modern_settings_focus();
#endif
    ui_system_settings_save();
}

// event funtions

///////////////// key function ///////////////////

#include "key.h"
void ui_set_page_key_handler(void *key_event)
{
    key_event_t *key = key_event;
    if (current_panel_index == 0 &&
        (key->id == KEY_ID_Y || key->id == KEY_ID_N)) {
        brightness_key(key);
        return;
    }
    if (key->type == KEY_EVT_CLICK &&
        (key->id == KEY_ID_B || key->id == KEY_ID_L || key->id == KEY_ID_R))
        brightness_stop();
    int panel_count = sizeof(panels) / sizeof(panels[0]);
    // key boot
    if (((key_event_t*)key_event)->id == KEY_ID_B && ((key_event_t*)key_event)->type == KEY_EVT_CLICK)
    {
        lv_lib_pm_goto_first();
        return;
    }
    // key left
    if (((key_event_t*)key_event)->id == KEY_ID_L && ((key_event_t*)key_event)->type == KEY_EVT_CLICK)
    {
        lv_obj_clear_state(panels[current_panel_index], LV_STATE_CHECKED);
        current_panel_index = (current_panel_index - 1 + panel_count) % panel_count;
        lv_obj_add_state(panels[current_panel_index], LV_STATE_CHECKED);
        scroll_focus();
#if POWER_PICO_UI_MODERN
        modern_settings_focus();
#endif
    }
    // key right
    else if (((key_event_t*)key_event)->id == KEY_ID_R && ((key_event_t*)key_event)->type == KEY_EVT_CLICK)
    {
        lv_obj_clear_state(panels[current_panel_index], LV_STATE_CHECKED);
        current_panel_index = (current_panel_index + 1) % panel_count;
        lv_obj_add_state(panels[current_panel_index], LV_STATE_CHECKED);
        scroll_focus();
#if POWER_PICO_UI_MODERN
        modern_settings_focus();
#endif
    }
    // key yes or key neg
    else if(((key_event_t*)key_event)->id == KEY_ID_Y || ((key_event_t*)key_event)->id == KEY_ID_N)
    {
        switch(current_panel_index)
        {
            // key sound
            case 1:
                // key yes
                if (((key_event_t*)key_event)->id == KEY_ID_Y && ((key_event_t*)key_event)->type == KEY_EVT_CLICK)
                {
                    lv_obj_add_state(ui_SwitchKS, LV_STATE_CHECKED);
                    ui_set_key_sound_enable(1);
                }
                // key neg
                else if (((key_event_t*)key_event)->id == KEY_ID_N && ((key_event_t*)key_event)->type == KEY_EVT_CLICK)
                {
                    lv_obj_clear_state(ui_SwitchKS, LV_STATE_CHECKED);
                    ui_set_key_sound_enable(0);
                }
                break;

            // language
            case 2:
                // key yes
                if (((key_event_t*)key_event)->id == KEY_ID_Y && ((key_event_t*)key_event)->type == KEY_EVT_CLICK)
                {
                    change_language(1);
                }
                // key neg
                else if (((key_event_t*)key_event)->id == KEY_ID_N && ((key_event_t*)key_event)->type == KEY_EVT_CLICK)
                {
                    change_language(0);
                }
                return;

            // chose rotation
            case 3:
                uint16_t rotation = ui_get_display_rotation();
                // key yes
                if (((key_event_t*)key_event)->id == KEY_ID_Y && ((key_event_t*)key_event)->type == KEY_EVT_CLICK)
                {
                    rotation = (rotation + 360 + 90) % 360;
                }
                // key neg
                else if (((key_event_t*)key_event)->id == KEY_ID_N && ((key_event_t*)key_event)->type == KEY_EVT_CLICK)
                {
                    rotation = (rotation + 360 - 90) % 360;
                }
                if (rotation == 0) {
                    lv_label_set_text(ui_LabelRotNum, "<  0  >");
                } else if (rotation == 90) {
                    lv_label_set_text(ui_LabelRotNum, "< 90 >");
                } else if (rotation == 180) {
                    lv_label_set_text(ui_LabelRotNum, "< 180 >");
                } else if (rotation == 270) {
                    lv_label_set_text(ui_LabelRotNum, "< 270 >");
                }
                ui_set_display_rotation(rotation);
                ui_full_screen_refresh(ui_SetPage);
                break;

            // current range
            case 4:
            {
                uint8_t mode = ui_get_current_range_mode();
                if (((key_event_t*)key_event)->id == KEY_ID_Y && ((key_event_t*)key_event)->type == KEY_EVT_CLICK)
                {
                    mode = (mode + 1U) % 4U;
                }
                else if (((key_event_t*)key_event)->id == KEY_ID_N && ((key_event_t*)key_event)->type == KEY_EVT_CLICK)
                {
                    mode = (mode + 3U) % 4U;
                }
                ui_set_current_range_mode(mode);
                _set_range_label_text(mode);
                break;
            }

            // PPS page
            case 5:
                // 发送开启PD诱骗的信号
                if (((key_event_t*)key_event)->id == KEY_ID_Y && ((key_event_t*)key_event)->type == KEY_EVT_CLICK)
                {
                    lv_lib_pm_goto("Power Page", 0);
                    return;
                }
                break;

            case 6:
#if POWER_PICO_UI_MODERN
                if (key->id == KEY_ID_Y && key->type == KEY_EVT_CLICK) {
                    lv_lib_pm_goto("Theme Page", 0);
                    return;
                }
                break;
            case 7:
#endif
                // about
                // do nothing
                break;
        }
#if POWER_PICO_UI_MODERN
        modern_settings_focus();
#endif
        // save settings to eeprom
        ui_system_settings_save();
    }
}

/////////////////////// para_initialize //////////////////////

static void on_setpage_loaded(lv_event_t * e) {
    // 当 SetPage 页面加载完成后，滚动到当前选中的 panel
    scroll_focus();
}

static void _setting_init(void) {

    // backlight
#if POWER_PICO_UI_MODERN
    /* Show absolute percent; brightness_apply still enforces the 10% floor. */
    lv_slider_set_range(ui_SliderBL, 0, 1000);
#else
    lv_slider_set_range(ui_SliderBL, 100, 1000);
#endif
    lv_slider_set_value(ui_SliderBL, ui_get_back_light_level() * 10, LV_ANIM_OFF);

    // key sound
    if(ui_get_key_sound_enable())
        lv_obj_add_state(ui_SwitchKS, LV_STATE_CHECKED);
    else
        lv_obj_clear_state(ui_SwitchKS, LV_STATE_CHECKED);

    // language
    if(ui_get_language_select() == 1)
        lv_obj_add_state(ui_SwitchLang, LV_STATE_CHECKED);
    else
        lv_obj_clear_state(ui_SwitchLang, LV_STATE_CHECKED);

    // lcd rotation
    uint16_t rotation = ui_get_display_rotation();
    if (rotation == 0) {
        lv_label_set_text(ui_LabelRotNum, "<  0  >");
    } else if (rotation == 90) {
        lv_label_set_text(ui_LabelRotNum, "< 90 >");
    } else if (rotation == 180) {
        lv_label_set_text(ui_LabelRotNum, "< 180 >");
    } else if (rotation == 270) {
        lv_label_set_text(ui_LabelRotNum, "< 270 >");
    }

    _set_range_label_text(ui_get_current_range_mode());
}

/////////////////////// ui_initialize //////////////////////

void ui_SetPage_screen_init(void)
{
    brightness_direction = 0;
    brightness_dirty = false;
#if POWER_PICO_UI_MODERN
#include "../modern/settings_layout.inc"
#else
    ui_SetPage = lv_obj_create(NULL);

    ui_PanelBL = lv_obj_create(ui_SetPage);
    lv_obj_set_width(ui_PanelBL, 234);
    lv_obj_set_height(ui_PanelBL, 65);
    lv_obj_set_x(ui_PanelBL, 0);
    lv_obj_set_y(ui_PanelBL, 5);
    lv_obj_set_align(ui_PanelBL, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_PanelBL, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_PanelBL, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelBL, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PanelBL, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_SliderBL = lv_slider_create(ui_PanelBL);
    lv_slider_set_value(ui_SliderBL, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBL) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderBL, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderBL, 200);
    lv_obj_set_height(ui_SliderBL, 10);
    lv_obj_set_align(ui_SliderBL, LV_ALIGN_BOTTOM_MID);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_SliderBL, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_SliderBL, lv_obj_get_style_pad_right(ui_SliderBL, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_LabelBL = lv_label_create(ui_PanelBL);
    lv_obj_set_width(ui_LabelBL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBL, 0);
    lv_obj_set_y(ui_LabelBL, -5);
    lv_label_set_text(ui_LabelBL, _("Screen Brightness :"));
    if(ui_get_language_select() == 0)
        lv_obj_set_style_text_font(ui_LabelBL, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    else
        lv_obj_set_style_text_font(ui_LabelBL, &ui_font_zhongyuan18, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_PanelKS = lv_obj_create(ui_SetPage);
    lv_obj_set_width(ui_PanelKS, 234);
    lv_obj_set_height(ui_PanelKS, 45);
    lv_obj_set_x(ui_PanelKS, 0);
    lv_obj_set_y(ui_PanelKS, 75);
    lv_obj_set_align(ui_PanelKS, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_PanelKS, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_PanelKS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelKS, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PanelKS, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_SwitchKS = lv_switch_create(ui_PanelKS);
    lv_obj_set_width(ui_SwitchKS, 50);
    lv_obj_set_height(ui_SwitchKS, 25);
    lv_obj_set_align(ui_SwitchKS, LV_ALIGN_RIGHT_MID);
    lv_obj_add_state(ui_SwitchKS, LV_STATE_CHECKED);       /// States

    ui_LabelKS = lv_label_create(ui_PanelKS);
    lv_obj_set_width(ui_LabelKS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelKS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelKS, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelKS, _("Enable key sound"));
    if(ui_get_language_select() == 0)
        lv_obj_set_style_text_font(ui_LabelKS, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    else
        lv_obj_set_style_text_font(ui_LabelKS, &ui_font_zhongyuan18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLang = lv_obj_create(ui_SetPage);
    lv_obj_set_width(ui_PanelLang, 234);
    lv_obj_set_height(ui_PanelLang, 45);
    lv_obj_set_x(ui_PanelLang, 0);
    lv_obj_set_y(ui_PanelLang, 125);
    lv_obj_set_align(ui_PanelLang, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_PanelLang, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_PanelLang, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelLang, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PanelLang, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_SwitchLang = lv_switch_create(ui_PanelLang);
    lv_obj_set_width(ui_SwitchLang, 50);
    lv_obj_set_height(ui_SwitchLang, 25);
    lv_obj_set_align(ui_SwitchLang, LV_ALIGN_RIGHT_MID);

    ui_LabelLang = lv_label_create(ui_PanelLang);
    lv_obj_set_width(ui_LabelLang, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLang, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelLang, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelLang, _("Enable Chinese"));
    if(ui_get_language_select() == 0)
        lv_obj_set_style_text_font(ui_LabelLang, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    else
        lv_obj_set_style_text_font(ui_LabelLang, &ui_font_zhongyuan18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelRotate = lv_obj_create(ui_SetPage);
    lv_obj_set_width(ui_PanelRotate, 234);
    lv_obj_set_height(ui_PanelRotate, 45);
    lv_obj_set_x(ui_PanelRotate, 0);
    lv_obj_set_y(ui_PanelRotate, 175);
    lv_obj_set_align(ui_PanelRotate, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_PanelRotate, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_PanelRotate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelRotate, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PanelRotate, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_LabelRotation = lv_label_create(ui_PanelRotate);
    lv_obj_set_width(ui_LabelRotation, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRotation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelRotation, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelRotation, _("Chose Rotation"));
    if(ui_get_language_select() == 0)
        lv_obj_set_style_text_font(ui_LabelRotation, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    else
        lv_obj_set_style_text_font(ui_LabelRotation, &ui_font_zhongyuan18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRotNum = lv_label_create(ui_PanelRotate);
    lv_obj_set_width(ui_LabelRotNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRotNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelRotNum, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelRotNum, "< 180 >");
    lv_obj_set_style_text_font(ui_LabelRotNum, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelRange = lv_obj_create(ui_SetPage);
    lv_obj_set_width(ui_PanelRange, 234);
    lv_obj_set_height(ui_PanelRange, 45);
    lv_obj_set_x(ui_PanelRange, 0);
    lv_obj_set_y(ui_PanelRange, 225);
    lv_obj_set_align(ui_PanelRange, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_PanelRange, LV_OBJ_FLAG_CHECKABLE);
    lv_obj_remove_flag(ui_PanelRange, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_PanelRange, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PanelRange, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_LabelRange = lv_label_create(ui_PanelRange);
    lv_obj_set_width(ui_LabelRange, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LabelRange, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_LabelRange, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelRange, _("Current Range"));
    if(ui_get_language_select() == 0)
        lv_obj_set_style_text_font(ui_LabelRange, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    else
        lv_obj_set_style_text_font(ui_LabelRange, &ui_font_zhongyuan18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRangeMode = lv_label_create(ui_PanelRange);
    lv_obj_set_width(ui_LabelRangeMode, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_LabelRangeMode, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_LabelRangeMode, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelRangeMode, _("AUTO"));
    if(ui_get_language_select() == 0)
        lv_obj_set_style_text_font(ui_LabelRangeMode, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    else
        lv_obj_set_style_text_font(ui_LabelRangeMode, &ui_font_zhongyuan18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelPPS = lv_obj_create(ui_SetPage);
    lv_obj_set_width(ui_PanelPPS, 234);
    lv_obj_set_height(ui_PanelPPS, 45);
    lv_obj_set_x(ui_PanelPPS, 0);
    lv_obj_set_y(ui_PanelPPS, 275);
    lv_obj_set_align(ui_PanelPPS, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_PanelPPS, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_PanelPPS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelPPS, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PanelPPS, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_t *power_arrow = lv_label_create(ui_PanelPPS);
    lv_label_set_text(power_arrow, LV_SYMBOL_RIGHT);
    lv_obj_set_style_text_font(power_arrow, &lv_font_montserrat_16, 0);
    lv_obj_set_align(power_arrow, LV_ALIGN_RIGHT_MID);

    ui_LabelPPS = lv_label_create(ui_PanelPPS);
    lv_obj_set_width(ui_LabelPPS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelPPS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelPPS, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelPPS, _("PD Sink"));
    if(ui_get_language_select() == 0)
        lv_obj_set_style_text_font(ui_LabelPPS, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    else
        lv_obj_set_style_text_font(ui_LabelPPS, &ui_font_zhongyuan20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelAbout = lv_obj_create(ui_SetPage);
    lv_obj_set_width(ui_PanelAbout, 234);
    lv_obj_set_height(ui_PanelAbout, 100);
    lv_obj_set_x(ui_PanelAbout, 0);
    lv_obj_set_y(ui_PanelAbout, 325);
    lv_obj_set_align(ui_PanelAbout, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_PanelAbout, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_PanelAbout, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelAbout, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_PanelAbout, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_LabelAbout = lv_label_create(ui_PanelAbout);
    lv_obj_set_width(ui_LabelAbout, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAbout, LV_SIZE_CONTENT);    /// 1
    char str_buf[64];
    sprintf(str_buf, "About\nPower-Pico\nThe uA current meter\nV %d.%d.%d", pp_version_major(), pp_version_minor(), pp_version_patch());
    lv_label_set_text(ui_LabelAbout, str_buf);
    lv_obj_set_style_text_font(ui_LabelAbout, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

#endif
    // init setting values
    _setting_init();
    brightness_timer = lv_timer_create(brightness_update, 20, NULL);
    lv_timer_pause(brightness_timer);

    // store panels in array
    panels[0] = ui_PanelBL;
    panels[1] = ui_PanelKS;
    panels[2] = ui_PanelLang;
    panels[3] = ui_PanelRotate;
    panels[4] = ui_PanelRange;
    panels[5] = ui_PanelPPS;
#if POWER_PICO_UI_MODERN
    panels[6] = ui_PanelTheme;
    panels[7] = ui_PanelAbout;
#else
    panels[6] = ui_PanelAbout;
#endif
    lv_obj_add_state(panels[current_panel_index], LV_STATE_CHECKED);
#if POWER_PICO_UI_MODERN
    modern_settings_focus();
#endif

    // timer
    /* Negotiation is owned by the power menu, not this settings list. */

    //
    lv_obj_add_event_cb(ui_SetPage, on_setpage_loaded, LV_EVENT_SCREEN_LOADED, NULL);

}

void ui_SetPage_screen_destroy(void)
{
    brightness_stop();
    if (brightness_timer) lv_timer_delete(brightness_timer);
    brightness_timer = NULL;
}
